export default {
  startJourney: 'steering',
  finishJourney: 'flag-checkered',
  fleet: 'car-multiple',
  confirm: 'check',
  scan: 'camera',
  save: 'content-save',
  retry: 'reload',
  addItem: 'plus',
  unfoldList: 'menu-down',
  report: 'pdf-box',
  cancel: 'close-circle',
  people: 'account-multiple',
  dry: 'weather-sunny',
  wet: 'weather-rainy',
  fog: 'weather-fog',
  snow: 'weather-snowy-heavy',
  hail: 'weather-hail',
};
