import Constants from '../res/Constants';

const km = ' km';

export default {
  appName: 'Fahrtenbuch',
  startJourney: 'Fahrt beginnen',
  finishJourney: 'Fahrt beenden',
  saveJourney: 'Fahrt speichern',
  cameraPermission: 'Kamera-Berechtigung',
  cameraPermissionMessage: 'Kamera verwenden, um Kilometerstand zu erfassen',
  agree: 'Zustimmen',
  deny: 'Ablehnen',
  modelDownloadMessage: 'Texterkennungsmodell wird heruntergeladen...',
  mileage: 'Kilometerstand',
  scanMileage: 'Kilometerstand erfassen',
  confirm: 'Bestätigen',
  enterDetails: 'Details eingeben',
  route: 'Strecke',
  weather: 'Wetter',
  enterMileageMessage: 'Kilometerstand eingeben oder abfotografieren',
  loadingMessage: 'Deine Fahrten werden geladen...',
  negativeDistanceMessage: 'Kilometerstand muss höher sein als zu Beginn der Fahrt',
  highDistanceMessage: 'Da stimmt etwas nicht. Oder bist du wirklich über 10.000 km gefahren?',
  editVehicles: 'Fahrzeuge bearbeiten',
  addVehicle: 'Fahrzeug hinzufügen',
  vehicleName: 'Name des Fahrzeugs',
  numberPlate: 'Kennzeichen',
  saveVehicle: 'Fahrzeug speichern',
  enterNameMessage: 'Name eingeben',
  enterNumberPlateMessage: 'Kennzeichen eingeben',
  vehicle: 'Fahrzeug',
  lowMileageMessage: 'Kilometerstand muss höher sein als bei der letzten Fahrt mit dem ',
  madeIt: 'Geschafft!',
  km: km,
  kmToGo: difference => 'noch ' + difference + km,
  date: 'Datum',
  distance: 'Distanz',
  start: 'Start',
  end: 'Ende',
  signature: 'Unteschrift',
  dayTime: 'Tageszeit',
  tutor: 'Begleiter',
  candidate: 'Bewerber',
  from: 'von',
  to: 'bis',
  morning: 'Morgen',
  forenoon: 'Vormittag',
  afternoon: 'Nachmittag',
  evening: 'Abend',
  night: 'Nacht',
  madeItMessage: 'Ich habe Ausbildungsfahrten im Ausmaß von ' + Constants.distanceGoal + km  + ' durchgeführt.',
  kmToGoMessage: difference => 'Mir fehlen noch Ausbildungsfahrten im Ausmaß von ' + difference + km + '.',
  total: 'Gesamt',
  sendTo: 'Senden an',
  createdWith: 'Erstellt mit der L17-Fahrtenbuch-App',
  ongoingJourneyMessage: (mileage, vehicleName) => 'Du hast bei' + km + ' ' + mileage + ' eine Fahrt\nmit dem ' + vehicleName + ' begonnen.',
  discardJourney: 'Fahrt verwerfen',
  ok: 'OK',
  cancel: 'Abbrechen',
  discardJourneyMessage: 'Die begonnene Fahrt wird gelöscht.',
  manageTutors: 'Begleiter verwalten',
  addTutor: 'Begleiter hinzufügen',
  saveTutor: 'Begleiter speichern',
  nickName: 'Spitzname',
  fullName: 'Vor- und Nachname',
  enterNickNameMessage: 'Spitzname eingeben',
  enterFullNameMessage: 'Vor- und Nachname eingeben',
  delimiter: ' · ',
  enterRouteMessage: 'Strecke eingeben',
  dry: 'trocken',
  wet: 'Regen / Nässe',
  fog: 'Nebel',
  snow: 'Schnee',
  hail: 'Hagel',
};
