export default {
  appName: 'Fahrtenbuch',
  startJourney: 'Fahrt beginnen',
  finishJourney: 'Fahrt beenden',
  saveJourney: 'Fahrt speichern',
  cameraPermission: 'Kamera-Berechtigung',
  cameraPermissionMessage: 'Kamera verwenden, um Kilometerstand zu erfassen',
  agree: 'Zustimmen',
  deny: 'Ablehnen',
  modelDownloadMessage: 'Texterkennungsmodell wird heruntergeladen...',
  mileage: 'Kilometerstand',
  scanMileage: 'Kilometerstand erfassen',
  confirm: 'Bestätigen',
  enterDetails: 'Details eingeben',
  route: 'Strecke',
  weather: 'Wetter',
};
