import Constants from '../res/Constants';

const km = ' km';

export default {
  appName: 'Fahrtenbuch',
  startJourney: 'Fahrt beginnen',
  finishJourney: 'Fahrt beenden',
  saveJourney: 'Fahrt speichern',
  editJourney: 'Fahrt bearbeiten',
  removeJourney: 'Fahrt entfernen',
  removeJourneyMessage: 'Die Fahrt wird unwiderruflich gelöscht.',
  cameraPermission: 'Zugriff auf Kamera erlauben',
  cameraPermissionMessage: 'Kamera verwenden, um Kilometerstand zu erfassen',
  memoryPermission: 'Speicherzugriff erlauben',
  memoryPermissionMessage: 'Expotierte PDF-Datei im Gerätespeicher ablegen',
  agree: 'Zustimmen',
  deny: 'Ablehnen',
  notNow: 'Jetzt nicht',
  modelDownloadMessage: 'Texterkennungsmodell wird heruntergeladen...',
  mileage: 'Kilometerstand',
  mileageAbbr: 'km-Stand',
  scanMileage: 'Kilometerstand erfassen',
  confirm: 'Bestätigen',
  enterDetails: 'Details eingeben',
  route: 'Strecke',
  weather: 'Wetter',
  enterMileageMessage: 'Kilometerstand eingeben oder abfotografieren',
  loadingMessage: 'Deine Fahrten werden geladen...',
  negativeDistanceMessage: 'Kilometerstand muss höher sein als zu Beginn der Fahrt',
  highDistanceMessage: 'Da stimmt etwas nicht. Oder bist du wirklich über 10.000 km gefahren?',
  manageVehicles: 'Fahrzeuge verwalten',
  addVehicle: 'Fahrzeug hinzufügen',
  editVehicle: 'Fahrzeug bearbeiten',
  removeVehicle: 'Fahrzeug entfernen',
  removeVehicleMessage: 'Alle Fahrten mit diesem Fahrzeug werden entfernt.',
  vehicleName: 'Name des Fahrzeugs',
  numberPlate: 'Kennzeichen',
  saveVehicle: 'Fahrzeug speichern',
  enterNameMessage: 'Name eingeben',
  enterNumberPlateMessage: 'Kennzeichen eingeben',
  enterStartMileageMessage: 'Start-Kilometerstand eingeben',
  enterEndMileageMessage: 'End-Kilometerstand eingeben',
  vehicle: 'Fahrzeug',
  lowMileageMessage: 'Kilometerstand muss höher sein als bei der letzten Fahrt mit dem ',
  madeIt: 'Geschafft!',
  km: km,
  kmToGo: difference => 'noch ' + difference + km,
  date: 'Datum',
  distance: 'Distanz',
  start: 'Start',
  end: 'Ende',
  signature: 'Unteschrift',
  dayTime: 'Tageszeit',
  tutor: 'Begleiter',
  candidate: 'Bewerber',
  from: 'von',
  to: 'bis',
  morning: 'Morgen',
  forenoon: 'Vormittag',
  afternoon: 'Nachmittag',
  evening: 'Abend',
  night: 'Nacht',
  madeItMessage: 'Ich habe Ausbildungsfahrten im Ausmaß von ' + Constants.distanceGoal + km  + ' durchgeführt.',
  kmToGoMessage: difference => 'Mir fehlen noch Ausbildungsfahrten im Ausmaß von ' + difference + km + '.',
  total: 'Gesamt',
  sendTo: 'Senden an',
  createdWith: 'Erstellt mit der L17-Fahrtenbuch-App',
  ongoingJourneyMessage: (mileage, vehicleName) => 'Du hast bei Kilometerstand ' + mileage + '\neine Fahrt mit dem ' + vehicleName + ' begonnen.',
  discardJourney: 'Fahrt verwerfen',
  ok: 'OK',
  cancel: 'Abbrechen',
  discardJourneyMessage: 'Die begonnene Fahrt wird gelöscht.',
  manageTutors: 'Begleiter verwalten',
  addTutor: 'Begleiter hinzufügen',
  saveTutor: 'Begleiter speichern',
  editTutor: 'Begleiter bearbeiten',
  removeTutor: 'Begleiter entfernen',
  removeTutorMessage: 'Alle Fahrten mit diesem Begleiter werden entfernt.',
  nickName: 'Spitzname',
  fullName: 'Vor- und Nachname',
  enterNickNameMessage: 'Spitzname eingeben',
  enterFullNameMessage: 'Vor- und Nachname eingeben',
  delimiter: ' · ',
  enterRouteMessage: 'Strecke eingeben',
  dry: 'trocken',
  wet: 'Nässe',
  fog: 'Nebel',
  snow: 'Schnee',
  hail: 'Hagel',
  negativeTimeMessage: 'Startzeit muss vor Endzeit liegen',
  share: 'Teilen',
  pdfExport: 'Fahrtenbuch exportieren',
  journeyStart: 'Fahrtbeginn',
  journeyEnd: 'Fahrtende',
};
