export const START_JOURNEY = 'START_JOURNEY';
export const FINISH_JOURNEY = 'FINISH_JOURNEY';
export const SAVE_JOURNEY = 'SAVE_JOURNEY';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const DISCARD_JOURNEY = 'DISCARD_JOURNEY';
